name: Analyze with CodeGuru Reviewer

on: [push]

permissions:
    id-token: write
    contents: read
    security-events: write 

jobs:
  build:
    name: Run CodeGuru Reviewer
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      continue-on-error: true
      id: iam-role
      with:
        role-to-assume: arn:aws:iam::245311248248:role/Admin-openid
        aws-region: eu-west-1
    
    - uses: actions/checkout@v2
      if: steps.iam-role.outcome == 'success'
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      if: steps.iam-role.outcome == 'success'
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      if: steps.iam-role.outcome == 'success'
      run: mvn compile -DskipTests

    - name: CodeGuru Reviewer
      if: steps.iam-role.outcome == 'success'
      id: codeguru
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: false
      with:          
        s3_bucket: 	codeguru-reviewer-github-profiler-demo-048169001733-uw2
        build_path: ./target/classes

    - name: Upload review result
      if: steps.iam-role.outcome == 'success' && steps.codeguru.outcome == 'success'
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
